### ISSUE TITLE
gradle and jmh

### ISSUE THREAD

**Issue by vadimnyc** [presidentio/teamcity-plugin-jmh#4]
Hello, would it be possible to make part of run from a gradle option? We are using gradle jmh plugin https://github.com/melix/jmh-gradle-plugin and it would be great if we can utilize JMH runner in teamcity.

**Comment by presidentio** [comment]
Hi, I will add this feature.

It will be very helpful once you provided me with simple gradle project with jmh.

**Comment by vadimnyc** [comment]
Hello,

great thank you! 
I created a very simple gradle/jmh project. If you run gradle jmh from the root it should build and generate jmh report under build/reports/jmh/. Please note that in gradle build/reports directory can be modified via DSL of gradle and referred as buildDir etc. 
Please find sample project attached.

There is two ways to start gradle depends if you are using gradle wrapper or not, so it either will be gradle or gradle.sh/bat

[jmhgradleSandbox.zip](https://github.com/presidentio/teamcity-plugin-jmh/files/203342/jmhgradleSandbox.zip)

**Comment by presidentio** [comment]
Hi,
I'm new with gradle. Can you please, advice me the sequence of gradle tasks which should be executed to get full classpath including newly compiled sources and all dependencies.

**Comment by vadimnyc** [comment]
Hi,

no worries. That is easy to help with! There are multiple ways to do it, but in case with jmh and assuming that jmh plugin is enabled in gradle (which should be the case for it). 
just run "gradlew jmhJar" or "gradlew clean jmhJar" and you should see under build/libs/jmhgradle sandbox-jmh.jar in this case. It's a far jar which will contain everything to run JMH.

If you just want a classpath (no JMH code generated) classes, other way can be is to add the following to build.gradle, apply plugin: 'java-library-distribution'

and run gradlew distTar or gradlew distZip and you will be able to see under build/distributions a archive of distribution

**Comment by presidentio** [comment]
Hi, could you, please, test [new release](https://github.com/presidentio/teamcity-plugin-jmh/releases/tag/v1.1.0). It includes maven and gradle support.

**Comment by vadimnyc** [comment]
I was on vacation. Will check tomorrow, thank you!

**Comment by vadimnyc** [comment]
Hello,
new release looks good. thank you!
