### ISSUE TITLE
Plugin fails to parse benchmarks.json

### ISSUE THREAD

**Issue by Argonaught** [presidentio/teamcity-plugin-jmh#5]
Hi Presidentio, 

I'm having an issue with the plugin parsing the benchmarks file. 
The Benchmarks tab in TeamCity displays the following error:
"Failed to load benchmarks for this build"

In the logs I found the following:
org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "warmupBatchSize" (Class com.presidentio.teamcity.jmh.entity.Benchmark), not marked as ignorable

I actually have a work around for this (grep -v BatchSize benchmarks.json), so it's not urgent, but it would be great if this could be fixed so I could remove the workaround.

P.S. Thanks for adding Gradle support!

example bencmarks.json:
[
    {
        "benchmark" : "jmh.MyBenchmark.testMethod",
        "mode" : "sample",
        "threads" : 16,
        "forks" : 10,
        "warmupIterations" : 20,
        "warmupTime" : "1 s",
        "warmupBatchSize" : 1,
        "measurementIterations" : 20,
        "measurementTime" : "1 s",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 107926.48986123124,
            "scoreError" : 15137.964135412896,
            "scoreConfidence" : [
                92788.52572581834,
                123064.45399664414
            ],
            "scorePercentiles" : {
                "0.0" : 202.0,
                "50.0" : 241.0,
                "90.0" : 129408.0,
                "95.0" : 144384.0,
                "99.0" : 167680.0,
                "99.9" : 345600.0,
                "99.99" : 7.9822848E7,
                "99.999" : 1.862270976E9,
                "99.9999" : 7.806083179375E9,
                "100.0" : 1.9260243968E10
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    61149.39472166627,
                    242646.7362758169,
                    133772.16198281822,
                    69871.88410339484,
                    88733.82642023677,
                    84500.93354988772,
                    49150.72104290572,
                    91409.90293362719,
                    94412.8547221831,
                    66350.76130727155,
                    61533.63026549899,
                    144453.1484069749,
                    34017.218332918106,
                    67286.86568784069,
                    105740.7198397738,
                    137676.27976895464,
                    527508.4279269367,
                    93670.01286853473,
                    199764.81211821616,
                    74895.56889208374
                ],
                [
                    72970.27248379236,
                    55021.10234847069,
                    53176.19851961344,
                    153066.63390333523,
                    85965.81947405828,
                    53742.931784427274,
                    333806.0982902764,
                    47523.343176338596,
                    303614.3280264032,
                    93388.1747306875,
                    87770.4721034899,
                    116972.63998670486,
                    87098.21871128684,
                    35616.4761091684,
                    132347.04122220213,
                    50581.80885890844,
                    60891.222659470805,
                    44513.90350947,
                    73810.08577940194,
                    194343.36374038094
                ],
                [
                    78974.40605035152,
                    96451.6643396014,
                    132201.6869388876,
                    80143.57755929585,
                    75342.22702768503,
                    113261.01195607442,
                    63649.03245133121,
                    56033.21321286536,
                    69074.42084666918,
                    109042.6163130339,
                    115130.4344382928,
                    74914.36854372986,
                    134840.2202402748,
                    118940.2701391989,
                    79690.05496335139,
                    86212.60050154757,
                    96496.53278635778,
                    198297.61463476927,
                    53559.47152907626,
                    51652.03923651452
                ],
                [
                    84682.1448591976,
                    90152.69831976386,
                    83582.88361634768,
                    287237.3943289381,
                    65142.425474445365,
                    128191.84563403884,
                    86205.8599663275,
                    46628.93987243912,
                    188252.59102828245,
                    49117.24709423653,
                    64340.96385863177,
                    67876.92145969662,
                    109303.00317987327,
                    90260.60007599178,
                    68533.04974220112,
                    241680.53273648207,
                    104888.5925966408,
                    87156.38389529467,
                    91077.44549367134,
                    113568.91034174449
                ],
                [
                    52274.72647055288,
                    151101.54670779104,
                    74758.12721744289,
                    106490.3406787763,
                    56061.003778429396,
                    171535.66789208754,
                    90211.54125231046,
                    320504.55570846074,
                    209472.3141029012,
                    277706.55579024396,
                    52437.813260016475,
                    76143.21561170123,
                    122605.67694667508,
                    115008.02403376049,
                    101025.08193900154,
                    81858.10978898562,
                    110904.3465003465,
                    63489.17338834053,
                    43483.0715806042,
                    89725.00583905246
                ],
                [
                    87186.51030423667,
                    68348.47411786787,
                    138610.853436109,
                    68025.10799846811,
                    72784.42505219791,
                    109007.84174015286,
                    82291.21273735506,
                    72342.59260131951,
                    201985.54490143587,
                    206493.82276576958,
                    59729.865043168975,
                    39035.11432873577,
                    55312.36313962543,
                    140439.46122817774,
                    46670.51947917921,
                    109063.65541708487,
                    31312.926242303896,
                    137001.42829971813,
                    295118.5797039643,
                    57411.63157433188
                ],
                [
                    43474.37785371168,
                    61967.098959778086,
                    88269.00058980408,
                    58932.85848025147,
                    165157.1015316144,
                    64246.81231400955,
                    50439.51279712086,
                    73072.49085683135,
                    48318.38865921971,
                    63570.048978727566,
                    98790.80570677218,
                    77901.66128892453,
                    223758.92780550636,
                    39007.273845381525,
                    88913.42020612532,
                    58183.66408136504,
                    119619.51148056616,
                    129425.93964339573,
                    163615.4470456853,
                    143052.12409528016
                ],
                [
                    33789.45499783989,
                    52936.81193162681,
                    66664.13121840915,
                    87228.43854093361,
                    27757.978923761686,
                    34036.26413446846,
                    43035.30745222989,
                    47410.820824447714,
                    159918.7437566255,
                    43999.73304693807,
                    94646.18626220836,
                    61839.97883895131,
                    63857.93159175603,
                    70119.53891238222,
                    96530.59037439631,
                    95797.52361592362,
                    87541.44525012535,
                    53334.18775175524,
                    65225.71689296096,
                    60441.942725870205
                ],
                [
                    159219.260099878,
                    74473.06534888594,
                    107073.70902502739,
                    189607.87488328665,
                    278707.2255874111,
                    87106.69299253303,
                    60481.00031137044,
                    88669.28270519503,
                    94862.80541915636,
                    104063.39481025244,
                    526553.4217208978,
                    431964.7288541923,
                    61955.71731586775,
                    83188.42663958,
                    177636.6768744368,
                    297617.77643983474,
                    66526.71987652204,
                    138147.5973884839,
                    124912.9909726474,
                    102957.00683164618
                ],
                [
                    166117.25186389463,
                    90470.44890272872,
                    349677.36148162914,
                    64642.42357790602,
                    340026.3455333626,
                    87567.19531141903,
                    262097.8712330388,
                    286369.24819545785,
                    132127.91460700877,
                    47532.04777996666,
                    139135.11205851144,
                    433620.62852483266,
                    92538.81028630161,
                    243874.19625546475,
                    149694.52810319306,
                    77153.83939263376,
                    100460.24698012845,
                    253434.4605185169,
                    249240.11042932238,
                    82119.31669328005
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    }
]

**Comment by presidentio** [comment]
Fixed by adding `@JsonIgnoreProperties(ignoreUnknown = true)`
