### ISSUE TITLE
Output tab doesn't show visual grouping/charting and color.

### ISSUE THREAD

**Issue by ronnc** [presidentio/teamcity-plugin-jmh#6]
Hi there,

Thanks for your work.

I've installed 1.1.1 and the output doesn't look like rich and colorful screenshot in your README.md

Is there anything I'm missing?

Regards,
Ronn

![image](https://cloud.githubusercontent.com/assets/19826227/15909894/de52d3c0-2e0b-11e6-9619-c7d3b2d29f96.png)

**Comment by presidentio** [comment]
Here is how it looks on my side http://home.presidentio.com:8111/viewLog.html?buildId=1931&buildTypeId=prairie_Benchmarks&tab=jmh .
Can I get access to you Teamcity? I need only guest user access for Benchmarks tab, to look for errors on the front end.

**Comment by ronnc** [comment]
Yea, nothing like what you have. Mine is pretty much just text only.

Our server is behind big corporate firewalls so can't get you access but here is the js console log.

viewLog.html:3972 Uncaught ReferenceError: bChart is not defined
viewLog.html:4028 Uncaught ReferenceError: bChart is not defined
http://daxa009s.unix.anz:9191/plugins/teamcity-plugin-jmh/css/bar.chart.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://daxa009s.unix.anz:9191/plugins/teamcity-plugin-jmh/css/jmh.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ronnc** [comment]
BTW we are on teamcity 8.1.5

**Comment by ronnc** [comment]
Ahh, the url is missing context root - "teamcity" before plugins and your server has teamcity bound to the root context so it doesn't have this problem.

e.g., it should be,

http://daxa009s.unix.anz:9191/**teamcity**/plugins/teamcity-plugin-jmh/css/bar.chart.css

**Comment by presidentio** [comment]
I guess it will help https://confluence.jetbrains.com/display/TCD9/Web+UI+Extensions#WebUIExtensions-ObtainingpathstoJSPfiles 

> Note: <c:url/> is required to construct correct URL in case if TeamCity is deployed under the non root context.

I'll look deeper on this soon.

**Comment by ronnc** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Great much appreciated. 

Sent from Yahoo Mail for iPhone

On Thursday, June 9, 2016, 7:23 PM, Vitaliy Gergel notifications@github.com wrote:

I guess it will help https://confluence.jetbrains.com/display/TCD9/Web+UI+Extensions#WebUIExtensions-ObtainingpathstoJSPfiles 

Note: is required to construct correct URL in case if TeamCity is deployed under the non root context.

I'll look on this soon.

**Comment by presidentio** [comment]
Try to use this release https://github.com/presidentio/teamcity-plugin-jmh/releases/tag/v1.1.2
And, please, let me know, does it works for you.

**Comment by ronnc** [comment]
That work a treat.

Thanks!
